### ISSUE TITLE
We lack a project plan / roadmap and are stagnating. 

### ISSUE THREAD

**Issue by not-inept** [triazo/EvoOS#1]
We need to hash out more specific requirements for each component, along with an agreed upon list of required components as we see it now.

EvoOS, EVOOS, EVOos, EVOS? We should pick one. I'm liking EvoOS the most, but currently even the readme _cough_ @droghio  _cough_ refers to it as EvoOS and EVOS. This is not entirely important, but I felt I should mention it.

Now, to get us moving.

EvoOS Main requirements:
What we have:
A thing that listens for signals and dispatches them somewhere else. We should be more specific about that, and probably ensure basic functionality requirements are met at some point.

Right now my points of confusion include the submodule loader (init_submodule in evmain.py) and how connected modules are loaded. 

That said, we should work on defining a module structure and formatting are modules to that for our next iteration of EvoOS. 

I think goals for the next waypoint should be:
-- Better/more clear module handling in EVMAIN (including more meaningful registration of modules / registration of modules, module specific / type specific event binding like in android (difference between using skype:// schema and tel:// schema) 
-- Input module: Assuming we're still using Julius, I don't think I've seen it yet, we should get a working input module that uses  our existing sound receive and returns a text command.

The way I'm imagining the flow of data is:

<img width="445" alt="sketch" src="https://cloud.githubusercontent.com/assets/2974730/9025385/e558720a-38d0-11e5-8f5a-04600c176a53.png">

Which means modules register events with evoos, events are triggered, and input streams are forwarded where they need to go until they create output. Which I think is what we all agreed upon to some extent. We should iron this out and explicitly state the desired interactions though, and work on developing a plan for moving forward. If we can iron out desired components either long or short term, we can break into chunks/features and start dishing things out.

**Comment by droghio** [comment]
1st My preference is for evoos or EvoOS, (@triazo I'm looking at you for the all caps). Here's what we have so far....

### EventHandler

Maintains a list of events and modules registered for those events. Allows module to register, add, and remove from events. Messages sent between modules and the **EventHandler** must follow the **message structure** guidelines listed below.

### Message Structure

Communication between modules and dispatcher is done with a via a json message packet prepended with 4 bytes that represent the message length. For example the message "{ event: 'addListener', lid: '0.0.0.0:4001', cbeid: 'testEvent' }" will need to be prepended with the number 65 which would be the byte sequence: "\x00\x00\x00\x65".

Current evoos commands are:
1. `addListener`
   Registers the lid for the event given in cbeid. When the event is sent to the dispatcher the module will be forwarded the message.
2. `removeListener`
   Removes the lid from the given cbeid.
3. `event`
   When sending an event id in the event field the dispatcher will forward the event to all listening modules. Additional information will also be sent to these modules if it is included in the original message.

There is a variety of unit tests and test modules included in the evoos deployment. There are also many util functions dedicated to common evoos tasks. Once we figure out what we want evoos to do we simply develop modules. The dispatcher should do as little as possible.

**Comment by not-inept** [comment]
We've made sufficient progress and will be forming a roadmap on the wiki while using issues as todos for tracking our weekly progress!
